### ISSUE TITLE
Blockchain, Tracking/Indexing of NFT Collection for User Ownership Verification and Display of NFT metadata

### ISSUE THREAD

**Issue by sebpalluel** [OfflineHQ/marketplace#58]
## Problem Statement
We need to track and index all our NFT Collections and Marketplaces in real-time, including changes happening outside of our platform. As NFTs can be transferred or sold freely, events like acquisition or transfer to another address should be detected regardless of where they occur.

## Potential Solutions
Here are some potential solutions along with their pros and cons:

### 1. External RPC Provider as an Indexer
We can use one or several external RPC providers to act as indexers for given NFT Collection contracts and Marketplaces. The updated results can be stored in a Redis cache, which we can query as needed.

#### Pros:

Can be implemented relatively quickly using available libraries.
Reliable providers with strong track records.

#### Cons:

Centralized solution, relies heavily on third-party services.
Scalability concerns as NFT Collections grow in number and transaction volume increases.

### 2. Decentralized Indexer (e.g., The Graph)
We can use a decentralized indexer like The Graph to track and index our NFT Collections.

#### Pros:

Decentralized solution, aligns well with the blockchain ethos.
Likely to be more future-proof as the blockchain ecosystem evolves.

#### Cons:

Dependability: The reliability of the service needs to be assessed.
Scalability: It's important to confirm if it can handle an increasing number of NFT Collections.

### 3. Cron Jobs for Periodic Querying
We could set up cron jobs to query our chosen providers every x minutes.

#### Pros:

Ensures regular updating of NFT ownership information.
Relatively easy to implement.

#### Cons:

Could be resource-intensive and slow as NFT Collections grow.
Frequency of updates might not be sufficient to capture all changes in real-time.

### 4. Event Querying Service for Transfer Events
We could rely on an event querying service to query the contract only when a transfer happens.

#### Pros:

Only queries when changes occur, potentially more efficient.
Can provide near real-time updates of ownership changes.

#### Cons:

Risk of missing events if backend service is interrupted.
Requires more complex error-handling and potential fallback mechanisms.

## Next Steps
Given these considerations, we need to decide on a primary solution and potentially a combination of approaches. Factors we need to consider include the reliability, decentralization, and scalability of the solution, as well as the complexity of implementation and the resources required.

A preliminary suggestion could be to use a combination of the solutions:

- An Event Querying Service as our primary method of tracking ownership changes in real-time.

- Periodic Cron Jobs as a fallback mechanism to ensure we capture any events that were missed due to backend downtime.

- Using a decentralized service like The Graph as a secondary, confirmatory source of truth, if reliability and scalability confirmations are satisfactory.

## Let's discuss this further to finalize the best approach for our requirements.
This version should provide a more detailed overview of the problem and possible solutions.

**Comment by sebpalluel** [comment]
### Ticket: Implementation of NFT Indexer for QR Code Transfer and `eventPassOwned` Creation

---

#### Objective:
To develop an indexer that efficiently tracks NFT transfers across addresses, specifically focused on transferring QR codes. Additionally, if an `eventPassOwned` does not exist for the transferred NFT, the system should automatically generate one.

#### Background:
With the increasing number of NFT transactions, there's a need for an automated mechanism to handle the complexities of transfers. This is particularly crucial for the QR code-based NFTs associated with `eventPassOwned`. Properly indexed data will not only ensure seamless user experience but also uphold the integrity and security of the transfers.

#### Specifications:

- [x] **Event Listener:** 
   - Establish an event listener to monitor the `Transfer` event of the specific NFT smart contract. This event typically emits the sender's address, receiver's address, and the token ID.
   - Ensure robust error-handling to account for potential downtimes or missed events.

- [x] **QR Code Transfer Mechanism:**
   - Upon detecting a transfer event, retrieve the associated QR code.
   - Transfer the QR code to the new owner’s address directory/storage securely.
   - Ensure encryption during the transfer process to uphold privacy and security.

- [ ] **`eventPassOwned` Verification & Creation:**
   - Post-transfer, check if the NFT has an associated `eventPassOwned`.
   - If not found, automatically generate a new `eventPassOwned` entry linked to the NFT's token ID.
   - Ensure the integrity of the `eventPassOwned` creation process, using cryptographic proofs if necessary.

- [ ] **Fallback Mechanism:**
   - Implement a periodic scan (e.g., every 24 hours) to cross-verify the results and ensure no missed transfers.
   - This scan should also account for any missed `eventPassOwned` entries.

- [ ] **Logging and Alerts:**
   - Log all transfers, successful QR code transfers, and `eventPassOwned` creations.
   - If any discrepancy or error occurs, an alert should be sent to the operations team for immediate resolution.

#### Testing:

1. **Unit Tests:** For all core functionalities, especially QR code transfer and `eventPassOwned` creation.
2. **Integration Tests:** To ensure seamless interaction between all components.
3. **Load Tests:** To check the robustness of the system under heavy traffic.
4. **Security Tests:** To uncover potential vulnerabilities or breaches.

**Comment by sebpalluel** [comment]
https://medium.com/coinmonks/top-10-indexed-blockchain-data-apis-providers-3a43da97e54c

**Comment by sebpalluel** [comment]
## Alchemy Webhooks
- https://docs.alchemy.com/reference/sdk-createwebhook
- https://docs.alchemy.com/reference/sdk-getnftfilters
- https://docs.alchemy.com/reference/nft-activity-webhook

## Alchemy NFT methods
- https://docs.alchemy.com/reference/sdk-getnftsforcontractiterator
- https://docs.alchemy.com/reference/sdk-gettransfersforcontract
- https://docs.alchemy.com/reference/sdk-verifynftownership
- https://docs.alchemy.com/reference/sdk-getnfts

**Comment by sebpalluel** [comment]
## Webhooks with Next.js
- https://github.com/shadcn-ui/taxonomy/blob/main/app/api/webhooks/stripe/route.ts
- Securing web hooks in nextjs with alchemy signature: https://github.com/alchemyplatform/webhook-examples/tree/master/node-express

https://makerkit.dev/blog/tutorials/nextjs13
```ts
 
export async function POST(
  request: Request
) {
  const rawBody = await request.text();
 
  // handle webhook here
}
```
