### ISSUE TITLE
Web, integrate vercel kv

### ISSUE THREAD

**Issue by sebpalluel** [OfflineHQ/marketplace#94]
## Project Task: Setting Up Docker Compose Environment

**Objective:** Properly configure the development environment for Vercel KV and Redis.

### Task 1: Install Vercel KV Server and Redis

- [x] In the `docker-compose.yaml` file, install the Vercel KV server along with Redis by following the instructions outlined [here](https://github.com/vercel/storage/issues/281#issuecomment-1650439329). Additional information is available [here](https://github.com/hiett/serverless-redis-http).

### Task 2: Define Environment Variables

- [x] Define the necessary port and URL configurations in the `.env.local` file:

```env
   KV_URL
   KV_REST_API_URL
   KV_REST_API_TOKEN
   KV_REST_API_READ_ONLY_TOKEN
```

### Task 3: Configure Testing Environment

- [x] Set up a testing environment in the `tools/test/docker-compose.yml` file. Ensure that a different port is used for testing purposes.

- [x] Update the `tools/test/isServicesLaunched.js` script to include a check for the readiness of the Redis server before initiating tests.

-  [x] Define the port and URL configurations for testing in the `.env.test.jest` file.

## Project Task: Create Vercel KV Wrapper Library
**Objective:** Develop a Next.js library for handling Vercel KV interactions.

### Task 1: Create @next/cache Library
- [x] Create a new Next.js library named `@next/cache` within the `next/cache` folder.
- [x]  Develop the library to instantiate a `Cache` class, utilizing the Vercel KV SDK for single-store access (`kv`) and multiple-store access (`createClient`). Reference: [Vercel KV SDK Documentation](https://vercel.com/docs/storage/vercel-kv/kv-reference).

### Task 2: Implement Integration Testing
- [x] Create minimal integration tests to verify that the `@next/cache` library functions correctly in a local environment. These tests should be designed to run against the test Docker containers (so loaded with the right env variables, which should be the case when running the jest test).

## Project Task: Develop Test Utilities for Cache Management
**Objective**: Build utility functions for managing cache operations, using the `@next/cache` library.

### Task 1: Create `@test-utils/cache` Library
- [x] Establish a new library called `@test-utils/cache` for cache management.
- [x] Design a 'seed table' structure similar to the one found in `libs/test-utils/db/src/index.ts`.

### Task 2: Implement Cache Seeding
- [x] Develop a function to seed the cache with JSON data based on the seed table configuration. Store the JSON files in a designated folder named `test-utils/cache/seeds`.

### Task 3: Implement Cache Deletion
- [x] Create a function to delete specific cache entries based on the seed table settings.

### Task 4: Implement Bulk Seeding and Deletion
- [x] Design functions to seed and delete all cache entries as needed.
